'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class AnioLectivoCurso
    Public Property IDAnioLectivoCurso As Short
    Public Property AnioLectivo As Short
    Public Property IDCurso As Byte

    Public Overridable Property Entidades As ICollection(Of Entidad) = New HashSet(Of Entidad)
    Public Overridable Property Curso As Curso
    Public Overridable Property ComprobanteDetalle As ICollection(Of ComprobanteDetalle) = New HashSet(Of ComprobanteDetalle)
    Public Overridable Property AnioLectivoCursoImporte As ICollection(Of AnioLectivoCursoImporte) = New HashSet(Of AnioLectivoCursoImporte)

End Class
