'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class AnioLectivoCuota
    Public Property AnioLectivo As Short
    Public Property MesInicio As Byte
    Public Property IDCuotaTipo As Byte
    Public Property ImporteMatricula As Decimal
    Public Property ImporteCuota As Decimal

    Public Overridable Property CuotaTipo As CuotaTipo

End Class
