'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Articulo
    Public Property IDArticulo As Short
    Public Property Nombre As String
    Public Property Descripcion As String
    Public Property DescripcionCorta As String
    Public Property IDArticuloGrupo As Byte
    Public Property EsActivo As Boolean
    Public Property IDUsuarioCreacion As Short
    Public Property FechaHoraCreacion As Date
    Public Property IDUsuarioModificacion As Short
    Public Property FechaHoraModificacion As Date

    Public Overridable Property ArticuloGrupo As ArticuloGrupo
    Public Overridable Property ComprobanteDetalles As ICollection(Of ComprobanteDetalle) = New HashSet(Of ComprobanteDetalle)
    Public Overridable Property ArticuloTalles As ICollection(Of ArticuloTalle) = New HashSet(Of ArticuloTalle)
    Public Overridable Property ListaPrecioArticulos As ICollection(Of ListaPrecioArticulo) = New HashSet(Of ListaPrecioArticulo)
    Public Overridable Property UsuarioCreacion As Usuario
    Public Overridable Property UsuarioModificacion As Usuario

End Class
