'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ArticuloGrupo
    Public Property IDArticuloGrupo As Byte
    Public Property IDArticuloGrupo_Padre As Nullable(Of Byte)
    Public Property Nombre As String
    Public Property EsActivo As Boolean
    Public Property IDUsuarioCreacion As Short
    Public Property FechaHoraCreacion As Date
    Public Property IDUsuarioModificacion As Short
    Public Property FechaHoraModificacion As Date
    Public Property IDConcepto As Byte
    Public Property EsRegistrable As Boolean
    Public Property EsStockeable As Boolean
    Public Property UtilizaColor As Boolean
    Public Property UtilizaTalle As Boolean

    Public Overridable Property Articulo As ICollection(Of Articulo) = New HashSet(Of Articulo)
    Public Overridable Property Concepto As Concepto

End Class
