'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Caja
    Public Property IDCaja As Byte
    Public Property Nombre As String
    Public Property IDBanco As Nullable(Of Short)
    Public Property Cuenta As String
    Public Property EsActivo As Boolean
    Public Property IDUsuarioCreacion As Short
    Public Property FechaHoraCreacion As Date
    Public Property IDUsuarioModificacion As Short
    Public Property FechaHoraModificacion As Date
    Public Property EmiteCheque As Boolean

    Public Overridable Property ComprobanteMedioPago As ICollection(Of ComprobanteMedioPago) = New HashSet(Of ComprobanteMedioPago)
    Public Overridable Property MedioPago As ICollection(Of MedioPago) = New HashSet(Of MedioPago)
    Public Overridable Property Chequeras As ICollection(Of Chequera) = New HashSet(Of Chequera)
    Public Overridable Property UsuarioCreacion As Usuario
    Public Overridable Property UsuarioModificacion As Usuario

End Class
