'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Cheque
    Public Property IDCheque As Integer
    Public Property IDBanco As Integer
    Public Property Serie As String
    Public Property Numero As String
    Public Property Fecha As Date
    Public Property FechaPago As Date
    Public Property Importe As Decimal
    Public Property CuentaBancaria As String
    Public Property IDUsuarioCreacion As Short
    Public Property FechaHoraCreacion As Date
    Public Property IDUsuarioModificacion As Short
    Public Property FechaHoraModificacion As Date

    Public Overridable Property Banco As Banco

End Class
