'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Comprobante
    Public Property IDComprobante As Integer
    Public Property IDComprobanteTipo As Byte
    Public Property PuntoVenta As String
    Public Property Numero As String
    Public Property NumeroCompleto As String
    Public Property FechaEmision As Date
    Public Property FechaVencimiento As Nullable(Of Date)
    Public Property IDConcepto As Nullable(Of Byte)
    Public Property FechaServicioDesde As Nullable(Of Date)
    Public Property FechaServicioHasta As Nullable(Of Date)
    Public Property IDEntidad As Integer
    Public Property ApellidoNombre As String
    Public Property IDDocumentoTipo As Byte
    Public Property DocumentoNumero As String
    Public Property IDCategoriaIVA As Byte
    Public Property DomicilioCalleCompleto As String
    Public Property DomicilioCodigoPostal As String
    Public Property DomicilioIDProvincia As Nullable(Of Byte)
    Public Property DomicilioIDLocalidad As Nullable(Of Short)
    Public Property Leyenda As String
    Public Property ImporteSubtotal As Decimal
    Public Property ImporteImpuesto As Decimal
    Public Property ImporteTotal As Decimal
    Public Property Notas As String
    Public Property CAE As String
    Public Property CAEVencimiento As Nullable(Of Date)
    Public Property IDComprobanteLote As Nullable(Of Integer)
    Public Property PeriodoContableAnio As Nullable(Of Short)
    Public Property PeriodoContableMes As Nullable(Of Byte)
    Public Property IDUsuarioCreacion As Short
    Public Property FechaHoraCreacion As Date
    Public Property IDUsuarioModificacion As Short
    Public Property FechaHoraModificacion As Date
    Public Property IDUsuarioAnulacion As Nullable(Of Short)
    Public Property FechaHoraAnulacion As Nullable(Of Date)
    Public Property IDUsuarioTransmisionAFIP As Nullable(Of Short)
    Public Property FechaHoraTransmisionAFIP As Nullable(Of Date)
    Public Property IDUsuarioEnvioEmail As Nullable(Of Short)
    Public Property FechaHoraEnvioEmail As Nullable(Of Date)

    Public Overridable Property CategoriaIVA As CategoriaIVA
    Public Overridable Property ComprobanteDetalle As ICollection(Of ComprobanteDetalle) = New HashSet(Of ComprobanteDetalle)
    Public Overridable Property ComprobanteImpuesto As ICollection(Of ComprobanteImpuesto) = New HashSet(Of ComprobanteImpuesto)
    Public Overridable Property ComprobanteMedioPago As ICollection(Of ComprobanteMedioPago) = New HashSet(Of ComprobanteMedioPago)
    Public Overridable Property ComprobanteLote As ComprobanteLote
    Public Overridable Property ComprobanteTipo As ComprobanteTipo
    Public Overridable Property Entidad As Entidad
    Public Overridable Property Localidad As Localidad
    Public Overridable Property UsuarioCreacion As Usuario
    Public Overridable Property UsuarioModificacion As Usuario
    Public Overridable Property ComprobanteAplicacion_Aplicantes As ICollection(Of ComprobanteAplicacion) = New HashSet(Of ComprobanteAplicacion)
    Public Overridable Property ComprobanteAplicacion_Aplicados As ICollection(Of ComprobanteAplicacion) = New HashSet(Of ComprobanteAplicacion)
    Public Overridable Property UsuarioEnvioEmail As Usuario
    Public Overridable Property Concepto As Concepto
    Public Overridable Property DocumentoTipo As DocumentoTipo
    Public Overridable Property EmailEnvio As ICollection(Of EmailEnvio) = New HashSet(Of EmailEnvio)

End Class
