'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ComprobanteImpuesto
    Public Property IDComprobante As Integer
    Public Property Indice As Byte
    Public Property IDImpuesto As Short

    Public Overridable Property Impuesto As Impuesto
    Public Overridable Property Comprobante As Comprobante

End Class
