'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ComprobanteAplicacion
    Public Property IDComprobanteAplicante As Integer
    Public Property IDComprobanteAplicado As Integer
    Public Property Importe As Decimal

    Public Overridable Property ComprobanteAplicado As Comprobante
    Public Overridable Property ComprobanteAplicante As Comprobante

End Class
