'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ComprobanteDetalle
    Public Property IDComprobante As Integer
    Public Property Indice As Byte
    Public Property IDArticulo As Short
    Public Property IDEntidad As Integer
    Public Property CuotaAnio As Nullable(Of Short)
    Public Property CuotaMes As Nullable(Of Byte)
    Public Property Cantidad As Nullable(Of Decimal)
    Public Property Unidad As String
    Public Property Descripcion As String
    Public Property PrecioUnitario As Decimal
    Public Property PrecioUnitarioDescuentoPorcentaje As Nullable(Of Decimal)
    Public Property PrecioUnitarioDescuentoImporte As Nullable(Of Decimal)
    Public Property PrecioUnitarioFinal As Decimal
    Public Property PrecioTotal As Decimal

    Public Overridable Property ComprobanteCabecera As ComprobanteCabecera

End Class
