'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ComprobanteAsociacion
    Public Property IDComprobanteAsociante As Integer
    Public Property IDComprobanteAsociado As Integer
    Public Property Motivo As String

    Public Overridable Property ComprobanteAsociado As Comprobante
    Public Overridable Property ComprobanteAsociante As Comprobante

End Class
