'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ComprobanteTipoPuntoVenta
    Public Property IDComprobanteTipo As Byte
    Public Property IDPuntoVenta As Byte
    Public Property UltimoNumero As String

    Public Overridable Property ComprobanteTipo As ComprobanteTipo
    Public Overridable Property PuntoVenta As PuntoVenta

End Class
