'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ComunicacionEntidad
    Public Property IDComunicacion As Short
    Public Property IDEntidad As Integer
    Public Property FechaHoraEnvioEmail As Date

    Public Overridable Property Comunicacion As Comunicacion
    Public Overridable Property Entidad As Entidad

End Class
