'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CursoAnioLectivo
    Public Property IDCurso As Byte
    Public Property AnioLectivo As Short
    Public Property ImporteMatricula As Decimal
    Public Property ImporteCuota As Decimal

End Class
