'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class DocumentoTipo
    Public Property IDDocumentoTipo As Byte
    Public Property Nombre As String
    Public Property EsActivo As Boolean
    Public Property VerificaModulo11 As Boolean

    Public Overridable Property Entidades As ICollection(Of Entidad) = New HashSet(Of Entidad)
    Public Overridable Property EntidadesFactura As ICollection(Of Entidad) = New HashSet(Of Entidad)
    Public Overridable Property Comprobante As ICollection(Of Comprobante) = New HashSet(Of Comprobante)

End Class
