'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class EntidadCurso
    Public Property IDEntidad As Integer
    Public Property AnioLectivo As Short
    Public Property IDCurso As Byte

    Public Overridable Property Entidad As Entidad
    Public Overridable Property Curso As Curso

End Class
