'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Entidad
    Public Property IDEntidad As Integer
    Public Property Apellido As String
    Public Property Nombre As String
    Public Property ApellidoNombre As String
    Public Property TipoPersonalColegio As Boolean
    Public Property TipoDocente As Boolean
    Public Property TipoAlumno As Boolean
    Public Property TipoFamiliar As Boolean
    Public Property TipoProveedor As Boolean
    Public Property TipoOtro As Boolean
    Public Property IDDocumentoTipo As Nullable(Of Byte)
    Public Property DocumentoNumero As String
    Public Property DocumentoNumeroVerificado As Boolean
    Public Property Genero As String
    Public Property FechaNacimiento As Nullable(Of Date)
    Public Property IDCategoriaIVA As Nullable(Of Byte)
    Public Property FacturaIDDocumentoTipo As Nullable(Of Byte)
    Public Property FacturaDocumentoNumero As String
    Public Property FacturaDocumentoNumeroVerificado As Boolean
    Public Property Telefono1 As String
    Public Property Telefono2 As String
    Public Property Telefono3 As String
    Public Property Email1 As String
    Public Property VerificarEmail1 As Boolean
    Public Property Email2 As String
    Public Property VerificarEmail2 As Boolean
    Public Property ComprobanteEnviarEmail As String
    Public Property DomicilioCalle1 As String
    Public Property DomicilioNumero As String
    Public Property DomicilioPiso As String
    Public Property DomicilioDepartamento As String
    Public Property DomicilioCalle2 As String
    Public Property DomicilioCalle3 As String
    Public Property DomicilioBarrio As String
    Public Property DomicilioCodigoPostal As String
    Public Property DomicilioIDProvincia As Nullable(Of Byte)
    Public Property DomicilioIDLocalidad As Nullable(Of Short)
    Public Property IDEntidadPadre As Nullable(Of Integer)
    Public Property IDEntidadMadre As Nullable(Of Integer)
    Public Property EmitirFacturaA As String
    Public Property IDEntidadTercero As Nullable(Of Integer)
    Public Property IDDescuento As Nullable(Of Byte)
    Public Property DescuentoOtroPorcentaje As Nullable(Of Decimal)
    Public Property FacturaIndividual As Boolean
    Public Property ExcluyeCalculoInteres As Boolean
    Public Property ExcluyeFacturaDesde As Nullable(Of Date)
    Public Property ExcluyeFacturaHasta As Nullable(Of Date)
    Public Property FacturaLeyenda As String
    Public Property DebitoAutomaticoTipo As String
    Public Property DebitoAutomaticoDirectoCBU As String
    Public Property EsActivo As Boolean
    Public Property Notas As String
    Public Property IDOtroSistema As Nullable(Of Integer)
    Public Property IDUsuarioCreacion As Short
    Public Property FechaHoraCreacion As Date
    Public Property IDUsuarioModificacion As Short
    Public Property FechaHoraModificacion As Date

    Public Overridable Property CategoriaIVA As CategoriaIVA
    Public Overridable Property DocumentoTipo As DocumentoTipo
    Public Overridable Property EntidadesPadres As ICollection(Of EntidadEntidad) = New HashSet(Of EntidadEntidad)
    Public Overridable Property EntidadesHijas As ICollection(Of EntidadEntidad) = New HashSet(Of EntidadEntidad)
    Public Overridable Property Localidad As Localidad
    Public Overridable Property UsuarioCreacion As Usuario
    Public Overridable Property UsuarioModificacion As Usuario
    Public Overridable Property EntidadMadreHijas As ICollection(Of Entidad) = New HashSet(Of Entidad)
    Public Overridable Property EntidadMadre As Entidad
    Public Overridable Property EntidadPadreHijas As ICollection(Of Entidad) = New HashSet(Of Entidad)
    Public Overridable Property EntidadPadre As Entidad
    Public Overridable Property AniosLectivosCursos As ICollection(Of AnioLectivoCurso) = New HashSet(Of AnioLectivoCurso)
    Public Overridable Property Descuento As Descuento
    Public Overridable Property ComprobanteDetalle As ICollection(Of ComprobanteDetalle) = New HashSet(Of ComprobanteDetalle)
    Public Overridable Property FacturaDocumentoTipo As DocumentoTipo
    Public Overridable Property EntidadTerceroAlumnos As ICollection(Of Entidad) = New HashSet(Of Entidad)
    Public Overridable Property EntidadTercero As Entidad
    Public Overridable Property Comprobante As ICollection(Of Comprobante) = New HashSet(Of Comprobante)
    Public Overridable Property ComunicacionEntidad As ICollection(Of ComunicacionEntidad) = New HashSet(Of ComunicacionEntidad)
    Public Overridable Property EntidadExportacion As ICollection(Of EntidadExportacion) = New HashSet(Of EntidadExportacion)
    Public Overridable Property EntidadPersonalColegio As EntidadPersonalColegio
    Public Overridable Property SueldosLiquidacionesEntidades As ICollection(Of SueldoLiquidacionEntidad) = New HashSet(Of SueldoLiquidacionEntidad)

End Class
