'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class EntidadGrupo
    Public Property IdEntidadGrupo As Byte
    Public Property Nombre As String
    Public Property Adicional As Nullable(Of Decimal)
    Public Property EsActivo As Boolean
    Public Property Notas As String
    Public Property IdUsuarioCreacion As Short
    Public Property FechaHoraCreacion As Date
    Public Property IdUsuarioModificacion As Short
    Public Property FechaHoraModificacion As Date

    Public Overridable Property UsuarioCreacion As Usuario
    Public Overridable Property UsuarioModificacion As Usuario
    Public Overridable Property EntidadesPersonalColegio As ICollection(Of EntidadPersonalColegio) = New HashSet(Of EntidadPersonalColegio)

End Class
