'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class EntidadEntidad
    Public Property IDEntidadPadre As Integer
    Public Property IDEntidadHija As Integer
    Public Property IDRelacionTipo As Byte
    Public Property TitularFactura As Boolean
    Public Property Notas As String
    Public Property CreacionIDUsuario As Byte
    Public Property CreacionFechaHora As Date
    Public Property ModificacionIDUsuario As Byte
    Public Property ModificacionFechaHora As Date

    Public Overridable Property EntidadHija As Entidad
    Public Overridable Property EntidadPadre As Entidad
    Public Overridable Property RelacionTipo As RelacionTipo

End Class
