'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Log
    Public Property IDLog As Integer
    Public Property IDUsuario As Byte
    Public Property Accion As String
    Public Property Descripcion As String

End Class
