Module Parametros
    'SISTEMA
    Friend Const INTERNET_PROXY As String = "INTERNET_PROXY"

    ' APLICACIÓN
    Friend Const APPLICATION_DATABASE_GUID As String = "APPLICATION_DATABASE_GUID"
    Friend Const LICENSE_COMPANY_NAME As String = "LICENSE_COMPANY_NAME"
    Friend Const USER_PASSWORD_MINIMUM_LENGHT As String = "USER_PASSWORD_MINIMUM_LENGHT"
    Friend Const USER_PASSWORD_SECURE_REQUIRED As String = "USER_PASSWORD_SECURE_REQUIRED"
    Friend Const EMAIL_VALIDATION_REGULAREXPRESSION As String = "EMAIL_VALIDATION_REGULAREXPRESSION"
    Friend Const ENTIDAD_VERIFICAR_EMAIL_AVISO As String = "ENTIDAD_VERIFICAR_EMAIL_AVISO"

    ' VALORES PREDETERMINADOS
    Friend Const DEFAULT_PROVINCIA_ID As String = "DEFAULT_PROVINCIA_ID"
    Friend Const DEFAULT_LOCALIDAD_ID As String = "DEFAULT_LOCALIDAD_ID"
    Friend Const DEFAULT_CODIGOPOSTAL As String = "DEFAULT_CODIGOPOSTAL"
    Friend Const DEFAULT_CATEGORIAIVA_ID As String = "DEFAULT_CATEGORIAIVA_ID"
    Friend Const DEFAULT_MONEDA_ID As String = "DEFAULT_MONEDA_ID"
    Friend Const DEFAULT_DOCUMENTOTIPO_ID As String = "DEFAULT_DOCUMENTOTIPO_ID"

    ' CUOTAS MENSUALES
    Friend Const CUOTA_MATRICULA_ARTICULO_ID As String = "CUOTA_MATRICULA_ARTICULO_ID"
    Friend Const CUOTA_MENSUAL_ARTICULO_ID As String = "CUOTA_MENSUAL_ARTICULO_ID"
    Friend Const CUOTA_MENSUAL_VENCIMIENTO1_DIA As String = "CUOTA_MENSUAL_VENCIMIENTO1_DIA"
    Friend Const CUOTA_MENSUAL_VENCIMIENTO2_DIA As String = "CUOTA_MENSUAL_VENCIMIENTO2_DIA"
    Friend Const CUOTA_MENSUAL_VENCIMIENTO3_DIA As String = "CUOTA_MENSUAL_VENCIMIENTO3_DIA"
    Friend Const CUOTA_MENSUAL_VENCIMIENTO2_INTERES As String = "CUOTA_MENSUAL_VENCIMIENTO2_INTERES"
    Friend Const CUOTA_MENSUAL_VENCIMIENTO3_INTERES As String = "CUOTA_MENSUAL_VENCIMIENTO3_INTERES"
    Friend Const CUOTA_MENSUAL_VENCIMIENTO_INTERES_REDONDEO As String = "CUOTA_MENSUAL_VENCIMIENTO_INTERES_REDONDEO"

    ' VARIOS
    Friend Const COMPROBANTE_ENTIDAD_MAYUSCULAS As String = "COMPROBANTE_ENTIDAD_MAYUSCULAS"
    Friend Const COMPROBANTE_APLICACION_INTERES_CALCULAR As String = "COMPROBANTE_APLICACION_INTERES_CALCULAR"
    Friend Const COMPROBANTE_APLICACION_INTERES_MENSUAL As String = "COMPROBANTE_APLICACION_INTERES_MENSUAL"
    Friend Const COMPROBANTE_APLICACION_INTERES_DIASTOLERANCIA As String = "COMPROBANTE_APLICACION_INTERES_DIASTOLERANCIA"
    Friend Const CONSUMIDORFINAL_DOCUMENTOTIPO_ID As String = "CONSUMIDORFINAL_DOCUMENTOTIPO_ID"
    Friend Const CONSUMIDORFINAL_DOCUMENTONUMERO As String = "CONSUMIDORFINAL_DOCUMENTONUMERO"

    ' AFIP WEB SERVICES
    Friend Const AFIP_WS_AA_HOMOLOGACION As String = "AFIP_WS_AA_HOMOLOGACION"
    Friend Const AFIP_WS_AA_PRODUCCION As String = "AFIP_WS_AA_PRODUCCION"
    Friend Const AFIP_WS_FE_HOMOLOGACION As String = "AFIP_WS_FE_HOMOLOGACION"
    Friend Const AFIP_WS_FE_PRODUCCION As String = "AFIP_WS_FE_PRODUCCION"

    ' EMPRESA
    Friend Const EMPRESA_CUIT As String = "EMPRESA_CUIT"
    Friend Const EMPRESA_RAZONSOCIAL As String = "EMPRESA_RAZONSOCIAL"
    Friend Const EMPRESA_DOMICILIOFISCAL_DIRECCION As String = "EMPRESA_DOMICILIOFISCAL_DIRECCION"
    Friend Const EMPRESA_DOMICILIOFISCAL_CODIGOPOSTAL As String = "EMPRESA_DOMICILIOFISCAL_CODIGOPOSTAL"
    Friend Const EMPRESA_DOMICILIOFISCAL_LOCALIDAD_ID As String = "EMPRESA_DOMICILIOFISCAL_LOCALIDAD_ID"
    Friend Const EMPRESA_DOMICILIOFISCAL_PROVINCIA_ID As String = "EMPRESA_DOMICILIOFISCAL_PROVINCIA_ID"
    Friend Const EMPRESA_CATEGORIAIVA_ID As String = "EMPRESA_CATEGORIAIVA_ID"
    Friend Const EMPRESA_IIBB_NUMERO As String = "EMPRESA_IIBB_NUMERO"
    Friend Const EMPRESA_INICIO_ACTIVIDAD As String = "EMPRESA_INICIO_ACTIVIDAD"
    Friend Const EMPRESA_PRISMA_NUMERO As String = "EMPRESA_PRISMA_NUMERO"
    Friend Const EMPRESA_ADDI_CODIGOSERVICIO As String = "EMPRESA_ADDI_CODIGOSERVICIO"
End Module
