'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class SueldoConcepto
    Public Property IdSueldoConcepto As Short
    Public Property Codigo As Nullable(Of Short)
    Public Property Nombre As String
    Public Property Tipo As String
    Public Property BaseCalculo As String
    Public Property Coeficiente As Nullable(Of Decimal)
    Public Property EsActivo As Boolean
    Public Property Notas As String
    Public Property IdUsuarioCreacion As Short
    Public Property FechaHoraCreacion As Date
    Public Property IdUsuarioModificacion As Short
    Public Property FechaHoraModificacion As Date

    Public Overridable Property SueldosCalculosModulo As ICollection(Of SueldoCalculoModulo) = New HashSet(Of SueldoCalculoModulo)
    Public Overridable Property UsuarioCreacion As Usuario
    Public Overridable Property UsuarioModificacion As Usuario

End Class
