'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class SueldoCalculoModulo
    Public Property Anio As Short
    Public Property Mes As Byte
    Public Property IdSueldoConcepto As Short
    Public Property Importe As Decimal
    Public Property IdUsuarioCreacion As Short
    Public Property FechaHoraCreacion As Date
    Public Property IdUsuarioModificacion As Short
    Public Property FechaHoraModificacion As Date

    Public Overridable Property SueldoConcepto As SueldoConcepto
    Public Overridable Property UsuarioCreacion As Usuario
    Public Overridable Property UsuarioModificacion As Usuario

End Class
