'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class SueldoLiquidacion
    Public Property IdSueldoLiquidacion As Short
    Public Property Anio As Short
    Public Property Mes As Byte
    Public Property BaseAntiguedadImporte As Nullable(Of Decimal)
    Public Property ModuloImporte As Nullable(Of Decimal)
    Public Property Notas As String
    Public Property IdUsuarioCreacion As Short
    Public Property FechaHoraCreacion As Date
    Public Property IdUsuarioModificacion As Short
    Public Property FechaHoraModificacion As Date

    Public Overridable Property UsuarioCreacion As Usuario
    Public Overridable Property UsuarioModificacion As Usuario
    Public Overridable Property SueldosLiquidacionesEntidades As ICollection(Of SueldoLiquidacionEntidad) = New HashSet(Of SueldoLiquidacionEntidad)

End Class
