'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class SueldoLiquidacionEntidad
    Public Property IdSueldoLiquidacion As Short
    Public Property IdEntidad As Integer
    Public Property ModuloCantidad As Nullable(Of Decimal)
    Public Property Antiguedad As Nullable(Of Decimal)
    Public Property Recibo1ImporteBasico As Nullable(Of Decimal)
    Public Property Recibo1ImporteNeto As Nullable(Of Decimal)
    Public Property Recibo2ImporteBasico As Nullable(Of Decimal)
    Public Property Recibo2ImporteNeto As Nullable(Of Decimal)
    Public Property Recibo3ImporteBasico As Nullable(Of Decimal)
    Public Property Recibo3ImporteNeto As Nullable(Of Decimal)
    Public Property Recibo4ImporteBasico As Nullable(Of Decimal)
    Public Property Recibo4ImporteNeto As Nullable(Of Decimal)
    Public Property Recibo5ImporteBasico As Nullable(Of Decimal)
    Public Property Recibo5ImporteNeto As Nullable(Of Decimal)

    Public Overridable Property Entidad As Entidad
    Public Overridable Property SueldoLiquidacion As SueldoLiquidacion

End Class
