'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class SueldoAntiguedad
    Public Property IdSueldoAntiguedad As Byte
    Public Property AntiguedadDesde As Byte
    Public Property Porcentaje As Decimal

End Class
