'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class SueldoLiquidacionEntidad
    Public Property IdSueldoLiquidacion As Short
    Public Property IdEntidad As Integer
    Public Property ModuloCantidad As Nullable(Of Decimal)
    Public Property Antiguedad As Nullable(Of Decimal)

    Public Overridable Property Entidad As Entidad
    Public Overridable Property SueldoLiquidacion As SueldoLiquidacion
    Public Overridable Property SueldosLiquidacionesEntidadesRecibos As ICollection(Of SueldoLiquidacionEntidadRecibo) = New HashSet(Of SueldoLiquidacionEntidadRecibo)

End Class
