Module Permisos

#Region "Constantes"

    Friend Const NIVEL As String = "NIVEL"

    Friend Const ANIO As String = "ANIO"
    Friend Const ANIO_AGREGAR As String = "ANIO_AGREGAR"
    Friend Const ANIO_EDITAR As String = "ANIO_EDITAR"
    Friend Const ANIO_ELIMINAR As String = "ANIO_ELIMINAR"

    Friend Const TURNO As String = "TURNO"

    Friend Const CURSO As String = "CURSO"
    Friend Const CURSO_AGREGAR As String = "CURSO_AGREGAR"
    Friend Const CURSO_EDITAR As String = "CURSO_EDITAR"
    Friend Const CURSO_ELIMINAR As String = "CURSO_ELIMINAR"

    Friend Const ANIOLECTIVOCURSO As String = "ANIOLECTIVOCURSO"
    Friend Const ANIOLECTIVOCURSO_AGREGAR As String = "ANIOLECTIVOCURSO_AGREGAR"
    Friend Const ANIOLECTIVOCURSO_EDITAR As String = "ANIOLECTIVOCURSO_EDITAR"
    Friend Const ANIOLECTIVOCURSO_ELIMINAR As String = "ANIOLECTIVOCURSO_ELIMINAR"

    Friend Const ANIOLECTIVOCURSOIMPORTE As String = "ANIOLECTIVOCURSOIMPORTE"
    Friend Const ANIOLECTIVOCURSOIMPORTE_AGREGAR As String = "ANIOLECTIVOCURSOIMPORTE_AGREGAR"
    Friend Const ANIOLECTIVOCURSOIMPORTE_EDITAR As String = "ANIOLECTIVOCURSOIMPORTE_EDITAR"
    Friend Const ANIOLECTIVOCURSOIMPORTE_ELIMINAR As String = "ANIOLECTIVOCURSOIMPORTE_ELIMINAR"

    Friend Const ANIOLECTIVOCUOTA As String = "ANIOLECTIVOCUOTA"
    Friend Const ANIOLECTIVOCUOTA_AGREGAR As String = "ANIOLECTIVOCUOTA_AGREGAR"
    Friend Const ANIOLECTIVOCUOTA_EDITAR As String = "ANIOLECTIVOCUOTA_EDITAR"
    Friend Const ANIOLECTIVOCUOTA_ELIMINAR As String = "ANIOLECTIVOCUOTA_ELIMINAR"

    Friend Const BANCO As String = "BANCO"
    Friend Const BANCO_AGREGAR As String = "BANCO_AGREGAR"
    Friend Const BANCO_EDITAR As String = "BANCO_EDITAR"
    Friend Const BANCO_ELIMINAR As String = "BANCO_ELIMINAR"

    Friend Const RELACIONTIPO As String = "RELACIONTIPO"

    Friend Const ENTIDAD As String = "ENTIDAD"
    Friend Const ENTIDAD_AGREGAR As String = "ENTIDAD_AGREGAR"
    Friend Const ENTIDAD_EDITAR As String = "ENTIDAD_EDITAR"
    Friend Const ENTIDAD_ELIMINAR As String = "ENTIDAD_ELIMINAR"
    Friend Const ENTIDAD_SINCRONIZAR_OUTLOOK As String = "ENTIDAD_SINCRONIZAR_OUTLOOK"
    Friend Const ENTIDAD_SINCRONIZAR_OUTLOOK_EDITAROPCIONES As String = "ENTIDAD_SINCRONIZAR_OUTLOOK_EDITAROPCIONES"

    Friend Const COMPROBANTE As String = "COMPROBANTE"
    Friend Const COMPROBANTE_AGREGAR As String = "COMPROBANTE_AGREGAR"
    Friend Const COMPROBANTE_EDITAR As String = "COMPROBANTE_EDITAR"
    Friend Const COMPROBANTE_ANULAR As String = "COMPROBANTE_ANULAR"
    Friend Const COMPROBANTE_ELIMINAR As String = "COMPROBANTE_ELIMINAR"
    Friend Const COMPROBANTE_IMPRIMIR As String = "COMPROBANTE_IMPRIMIR"
    Friend Const COMPROBANTE_IMPRIMIR_SINCAE As String = "COMPROBANTE_IMPRIMIR_SINCAE"
    Friend Const COMPROBANTE_GENERARLOTE As String = "COMPROBANTE_GENERARLOTE"
    Friend Const COMPROBANTE_TRANSMITIR_AFIP As String = "COMPROBANTE_TRANSMITIR_AFIP"
    Friend Const COMPROBANTE_ENVIAREMAIL As String = "COMPROBANTE_ENVIAREMAIL"
    Friend Const COMPROBANTE_EXPORTAR_PAGOMISCUENTAS As String = "COMPROBANTE_EXPORTAR_PAGOMISCUENTAS"
    Friend Const COMPROBANTE_EXPORTAR_SANTANDERDEBITODIRECTO As String = "COMPROBANTE_EXPORTAR_SANTANDERDEBITODIRECTO"
    Friend Const COMPROBANTE_EXPORTAR_SANTANDERRECAUDACIONPORCAJA As String = "COMPROBANTE_EXPORTAR_SANTANDERRECAUDACIONPORCAJA"
    Friend Const COMPROBANTE_IMPORTAR_SANTANDERDEBITODIRECTO As String = "COMPROBANTE_IMPORTAR_SANTANDERDEBITODIRECTO"
    Friend Const COMPROBANTE_IMPORTAR_SANTANDERRECAUDACIONPORCAJA As String = "COMPROBANTE_IMPORTAR_SANTANDERRECAUDACIONPORCAJA"
    Friend Const COMPROBANTE_DETALLE_PERMITE_MATRICULAANIOANTERIOR As String = "COMPROBANTE_DETALLE_PERMITE_MATRICULAANIOANTERIOR"
    Friend Const COMPROBANTE_DETALLE_PERMITE_CUOTAANIOSIGUIENTE As String = "COMPROBANTE_DETALLE_PERMITE_CUOTAANIOSIGUIENTE"
    Friend Const COMPROBANTE_DETALLE_PERMITE_CUOTAANIOANTERIORYSIGUIENTE As String = "COMPROBANTE_DETALLE_PERMITE_CUOTAANIOANTERIORYSIGUIENTE"

    Friend Const COMUNICACION As String = "COMUNICACION"
    Friend Const COMUNICACION_AGREGAR As String = "COMUNICACION_AGREGAR"
    Friend Const COMUNICACION_EDITAR As String = "COMUNICACION_EDITAR"
    Friend Const COMUNICACION_ELIMINAR As String = "COMUNICACION_ELIMINAR"
    Friend Const COMUNICACION_ENVIAREMAIL As String = "COMUNICACION_ENVIAREMAIL"

    Friend Const ENTIDADANIOLECTIVOCURSO As String = "ENTIDADANIOLECTIVOCURSO"
    Friend Const ENTIDADANIOLECTIVOCURSO_AGREGAR As String = "ENTIDADANIOLECTIVOCURSO_AGREGAR"
    Friend Const ENTIDADANIOLECTIVOCURSO_ELIMINAR As String = "ENTIDADANIOLECTIVOCURSO_ELIMINAR"
    Friend Const ENTIDADANIOLECTIVOCURSO_IMPRIMIR As String = "ENTIDADANIOLECTIVOCURSO_IMPRIMIR"

    Friend Const REPORTE As String = "REPORTE"

#End Region

    Friend Function VerificarPermiso(ByVal IDPermiso As String, Optional ByVal MostrarAviso As Boolean = True) As Boolean
        If pUsuario.IDUsuario = Constantes.USUARIO_ADMINISTRADOR Then
            Return True
        Else
            If pPermisos.Find(Function(usrper) usrper.IDUsuarioGrupo = pUsuario.IDUsuarioGrupo And usrper.IDPermiso.TrimEnd = IDPermiso) Is Nothing Then
                If MostrarAviso Then
                    MsgBox("No tiene autorización para realizar esta acción.", MsgBoxStyle.Exclamation, My.Application.Info.Title)
                End If
                Return False
            Else
                Return True
            End If
        End If
    End Function

    Friend Function LoadPermisos() As Boolean
        Try
            Using dbcontext As New CSColegioContext(True)
                pPermisos = dbcontext.UsuarioGrupoPermiso.ToList
            End Using
            Return True
        Catch ex As Exception
            CardonerSistemas.ErrorHandler.ProcessError(ex, "Error al cargar los Permisos del Usuario.")
            Return False
        End Try
    End Function

End Module
